pr: &pr {type: select, proxies: [ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸ”° èŠ‚ç‚¹é€‰æ‹©, ğŸš€ æ‰‹åŠ¨åˆ‡æ¢, DIRECT]}

p: &p {type: http, interval: 3600, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}

mode: rule
mixed-port: 51300
socks-port: 7898
port: 7899
allow-lan: true
log-level: info
ipv6: true
secret: '0513'
external-controller: 127.0.0.1:51225

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  use-system-hosts: false
  enhanced-mode: fake-ip
  fake-ip-range: 11.0.0.1/16
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  default-nameserver:
  - 8.8.8.8
  - 1.1.1.1
  - 223.5.5.5
  - 119.29.29.29
  nameserver:
  - https://8.8.8.8/dns-query
  - https://8.8.4.4/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  proxy-server-nameserver:
  - https://8.8.8.8/dns-query
  - https://8.8.4.4/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  nameserver-policy:
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query

tun:
  stack: gvisor
  device: Meta
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  strict-route: false
  mtu: 9000
  enable: true

proxy-providers:
  ğŸ›« æˆ‘çš„æœºåœº:
    <<: *p
    url: "https://example.com/xxx/xxx&flag=clash"
    path: ./proxies/airport.yaml

proxy-groups:
  - {name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸš€ æ‰‹åŠ¨åˆ‡æ¢, DIRECT]}
  - {name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢, type: select, include-all: true}

  - {name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯, <<: *pr}
  - {name: ğŸ’¬ OpenAi, <<: *pr}
  - {name: ğŸ¶ ç½‘æ˜“éŸ³ä¹, <<: *pr}
  - {name: ğŸ¶ Spotify, <<: *pr}
  - {name: ğŸ“¹ æ²¹ç®¡è§†é¢‘, <<: *pr}
  - {name: ğŸ¥ å¥ˆé£è§†é¢‘, <<: *pr}
  - {name: ğŸ“º å·´å“ˆå§†ç‰¹, <<: *pr}
  - {name: ğŸ“º å“”å“©å“”å“©, <<: *pr}
  - {name: ğŸŒ å›½å¤–åª’ä½“, <<: *pr}
  - {name: ğŸŒ å›½å†…åª’ä½“, <<: *pr}
  - {name: â“‚ï¸ å¾®è½¯æœåŠ¡, <<: *pr}
  - {name: ğŸ è‹¹æœæœåŠ¡, <<: *pr}
  - {name: ğŸ® æ¸¸æˆå¹³å°, <<: *pr}

  - {name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª, type: select, proxies: [REJECT, DIRECT]}
  - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [DIRECT, ğŸ”° èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ–¥ï¸ ç›´è¿è½¯ä»¶, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, <<: *pr}

  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, type: url-test, tolerance: 50, include-all-providers: true, filter: "(?i)æ¸¯|hk|hongkong|hong kong"}
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, type: url-test, tolerance: 50, include-all-providers: true, filter: "(?i)å°|tw|taiwan"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, type: url-test, tolerance: 50, include-all-providers: true, filter: "(?i)æ—¥æœ¬|jp|japan"}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, type: url-test, tolerance: 50, include-all-providers: true, filter: "(?i)æ–°|sg|singapore"}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, type: url-test, tolerance: 50, include-all-providers: true, filter: "(?i)ç¾|us|unitedstates|united states"}

rule-anchor:
  classical: &classical {type: http, interval: 86400, behavior: classical, format: text}

rule-providers:
  # è‹¥ä½¿ç”¨ ShellCrashï¼Œç”±äºæ— æ³•åˆ¤æ–­æœ¬æœºè¿›ç¨‹ï¼ˆé»˜è®¤ `find-process-mode: off`ï¼‰ï¼Œéœ€åˆ é™¤æ­¤æ¡ `applications`
  applications:
    <<: *classical
    path: ./ruleset/soratanmer/applications.list
    url: "https://raw.githubusercontent.com/soratanmer/ACL4SSR/main/Clash/Ruleset/applications.list"
  BanAD:
    <<: *classical
    path: ./ruleset/ACL4SSR/BanAD.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"
  BanProgramAD:
    <<: *classical
    path: ./ruleset/ACL4SSR/BanProgramAD.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"
  BanEasyList:
    <<: *classical
    path: ./ruleset/ACL4SSR/BanEasyList.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list"
  BanEasyListChina:
    <<: *classical
    path: ./ruleset/ACL4SSR/BanEasyListChina.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list"
  BanEasyPrivacy:
    <<: *classical
    path: ./ruleset/ACL4SSR/BanEasyPrivacy.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list"
  LocalAreaNetwork:
    <<: *classical
    path: ./ruleset/ACL4SSR/LocalAreaNetwork.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"
  UnBan:
    <<: *classical
    path: ./ruleset/ACL4SSR/UnBan.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"
  GoogleCN:
    <<: *classical
    path: ./ruleset/ACL4SSR/GoogleCN.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"
  SteamCN:
    <<: *classical
    path: ./ruleset/ACL4SSR/SteamCN.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list"
  OneDrive:
    <<: *classical
    path: ./ruleset/ACL4SSR/OneDrive.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list"
  Microsoft:
    <<: *classical
    path: ./ruleset/ACL4SSR/Microsoft.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"
  Apple:
    <<: *classical
    path: ./ruleset/ACL4SSR/Apple.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
  Telegram:
    <<: *classical
    path: ./ruleset/ACL4SSR/Telegram.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"
  OpenAi:
    <<: *classical
    path: ./ruleset/ACL4SSR/OpenAi.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list"
  Spotify:
    <<: *classical
    path: ./ruleset/ACL4SSR/Spotify.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Spotify.list"
  NetEaseMusic:
    <<: *classical
    path: ./ruleset/ACL4SSR/NetEaseMusic.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list"
  Epic:
    <<: *classical
    path: ./ruleset/ACL4SSR/Epic.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list"
  Origin:
    <<: *classical
    path: ./ruleset/ACL4SSR/Origin.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list"
  Sony:
    <<: *classical
    path: ./ruleset/ACL4SSR/Sony.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list"
  Steam:
    <<: *classical
    path: ./ruleset/ACL4SSR/Steam.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list"
  Nintendo:
    <<: *classical
    path: ./ruleset/ACL4SSR/Nintendo.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list"
  YouTube:
    <<: *classical
    path: ./ruleset/ACL4SSR/YouTube.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list"
  Netflix:
    <<: *classical
    path: ./ruleset/ACL4SSR/Netflix.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list"
  Bahamut:
    <<: *classical
    path: ./ruleset/ACL4SSR/Bahamut.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list"
  BilibiliHMT:
    <<: *classical
    path: ./ruleset/ACL4SSR/BilibiliHMT.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list"
  Bilibili:
    <<: *classical
    path: ./ruleset/ACL4SSR/Bilibili.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list"
  ChinaMedia:
    <<: *classical
    path: ./ruleset/ACL4SSR/ChinaMedia.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"
  ProxyMedia:
    <<: *classical
    path: ./ruleset/ACL4SSR/ProxyMedia.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"
  ProxyGFWlist:
    <<: *classical
    path: ./ruleset/ACL4SSR/ProxyGFWlist.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"
  ChinaDomain:
    <<: *classical
    path: ./ruleset/ACL4SSR/ChinaDomain.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
  ChinaCompanyIp:
    <<: *classical
    path: ./ruleset/ACL4SSR/ChinaCompanyIp.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"
  Download:
    <<: *classical
    path: ./ruleset/ACL4SSR/Download.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"

# è§„åˆ™
rules:
  # è‹¥ä½¿ç”¨ ShellCrashï¼Œç”±äºæ— æ³•åˆ¤æ–­æœ¬æœºè¿›ç¨‹ï¼ˆé»˜è®¤ `find-process-mode: off`ï¼‰ï¼Œéœ€åˆ é™¤æ­¤æ¡ `RULE-SET`
  - RULE-SET,applications,ğŸ–¥ï¸ ç›´è¿è½¯ä»¶
  - RULE-SET,BanAD,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,BanProgramAD,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,BanEasyList,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,BanEasyListChina,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,BanEasyPrivacy,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,LocalAreaNetwork,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,UnBan,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,GoogleCN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,OneDrive,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Telegram,ğŸ“² ç”µæŠ¥æ¶ˆæ¯
  - RULE-SET,OpenAi,ğŸ’¬ OpenAi
  - RULE-SET,NetEaseMusic,ğŸ¶ ç½‘æ˜“éŸ³ä¹
  - RULE-SET,Spotify,ğŸ¶ Spotify
  - RULE-SET,Epic,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Origin,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Sony,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Steam,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Nintendo,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,YouTube,ğŸ“¹ æ²¹ç®¡è§†é¢‘
  - RULE-SET,Bahamut,ğŸ“º å·´å“ˆå§†ç‰¹
  - RULE-SET,BilibiliHMT,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,Bilibili,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,ChinaMedia,ğŸŒ å›½å†…åª’ä½“
  - RULE-SET,ProxyMedia,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,ProxyGFWlist,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,ChinaDomain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ChinaCompanyIp,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Download,ğŸ¯ å…¨çƒç›´è¿
  - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
